#!/usr/bin/env bash
#This script prints 1-100 but at certain mutiples of 3 and 5 prints something diferent
for i in {1..100}; do
	if [ $((i % 3)) -eq 0 ] && [ $((i % 5)) -eq 0 ]; then
		echo "FizzBuzz"
	elif [ $((i % 3)) -eq 0 ]; then
		echo "Fizz"
	elif [ $((i % 5)) -eq 0 ]; then
		echo "Buzz"
 	else
	 printf "%d\n" "$i"
	fi
done
