#!/usr/bin/env bash
#This script displays username, user id and Home dir for the user

while IFS=':' read -r username _ userid _ _ homedir _; do
    echo "Username: $username, User ID: $userid, Home Directory: $homedir"
done < /etc/passwd
