#!/usr/bin/env bash
# This script uses a while loop to print out the numbers 1-20 but at certain numbers it changes behavior
i=1
while [ $i -le 20 ]
do
	printf "%d\n" "$i"
        case $i in 
        4)     
                printf "bad luck from China\n";;
        9)
                printf "bad luck from Japan\n";;
        17)
                printf "bad luck from Italy\n";;
        esac
        ((i++))
done
