#!/usr/bin/env bash
#This script acts as a clock all the way up to 12 hours and 59 minutes
h=0
m=1
   while [ $h -le 12 ]
   do
        while [ $m -le 59 ]
        do
        printf "%d\n" "$m"
	((m++))
        done
	if [ $m -eq 59 ];then
         m=1
         fi

   printf "%d\n" "Hour: $h"
   ((h++))
   done
