#!/usr/bin/env bash
#This script acts as a clock
h=0
m=1
   while [ $h -le 12 ]
   do
        echo "Hour: $h"
        while [ $m -le 59 ]
        do
        printf "%02d\n" "$m"
         ((m++))
        done
        ((h++))
        
   
   
   done
